dependencies:
  - name: nginx-ingress
    version: 0.18.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mongodb-replicaset
    version: 3.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: docker-registry
    version: 1.1.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: cert-manager
    version: 0.2.10
    repository: https://kubernetes-charts.storage.googleapis.com
