dependencies:
  - name: nginx-ingress 
    version: 0.8.16 
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mongodb-replicaset 
    version: 2.1.4 
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: docker-registry 
    version: 1.0.0 
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kube-lego 
    version: 0.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
