dependencies:
  - name: nginx-ingress
    version: 0.13.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: mongodb-replicaset
    version: 3.3.0
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: docker-registry
    version: 1.1.2
    repository: https://kubernetes-charts.storage.googleapis.com
  - name: kube-lego
    version: 0.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
