apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tsuru.fullname" . }}-docker-builder
  labels:
    app: {{ template "tsuru.name" . }}-docker-builder
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas.builder }} 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "tsuru.name" . }}-docker-builder
        release: {{ .Release.Name }}
    spec:
      hostname: {{ template "tsuru.fullname" . }}-docker-builder-1
      containers:
        - name: docker-cmds
          image: docker:stable
          command: ['docker', 'run', '-p', '80:80', 'httpd:latest']
          resources:
            requests:  
                cpu: 10m  
                memory: 256Mi 
          ports:
          - containerPort: 2375 
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
        - name: dind-daemon
          image: docker:stable-dind
          args: ['--insecure-registry={{ .Release.Name }}-docker-registry:5000']
          resources:
              requests:
                  cpu: 20m
                  memory: 512Mi
          securityContext:
              privileged: true
          ports:
            - containerPort: 2375
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-storage
          emptyDir: {}

