apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tsuru.fullname" . }}
  labels:
    app: {{ template "tsuru.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "tsuru.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "tsuru.fullname" . }}-tsuru-api
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: "{{ template "tsuru.fullname" . }}-api-config"
              mountPath: "/etc/tsuru"
      volumes:
        - name: {{ template "tsuru.fullname" . }}-api-config
          configMap:
            name: {{ template "tsuru.fullname" . }}-api-config
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
