apiVersion: v1
kind: Service
metadata:
  name: {{ template "tsuru.fullname" . }}-gandalf
  labels:
    app: {{ template "tsuru.name" . }}-gandalf
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP 
  clusterIP: None
  ports:
  - name: gandalfapi
    port: 8000
  - name: ssh
    port: 22
  selector:
    app: {{ template "tsuru.name" . }}-gandalf
    release: {{ .Release.Name }}
