{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "tsuru.fullname" . }}-tsuru-api
  labels:
    app: {{ template "tsuru.name" . }}-tsuru-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "update"]
- apiGroups: [""]
  resources: ["serviceaccounts", "namespaces"]
  verbs: ["create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/rollback"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/rollback"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "create", "update"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["delete", "get", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get"]
- apiGroups: ["tsuru.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tsuru.fullname" . }}-tsuru-api
  labels:
    app: {{ template "tsuru.name" . }}-tsuru-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tsuru.fullname" . }}-tsuru-api
subjects:
- kind: ServiceAccount
  name: {{ template "tsuru.fullname" . }}-tsuru-api
  namespace: default
{{- end -}}
