{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "tsuru.fullname" . }}-tsuru-api
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "update"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tsuru.fullname" . }}-tsuru-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tsuru.fullname" . }}-tsuru-api
subjects:
- kind: ServiceAccount
  name: {{ template "tsuru.fullname" . }}-tsuru-api
  namespace: default
{{- end -}}