{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
rules:
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
subjects:
- kind: ServiceAccount
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
  namespace: default
{{- end -}}