{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
  labels:
    app: {{ template "tsuru.name" . }}-kubernetes-router
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}