{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
  labels:
    app: {{ template "tsuru.name" . }}-kubernetes-router
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get"]
- apiGroups: ["tsuru.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
  labels:
    app: {{ template "tsuru.name" . }}-kubernetes-router
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
subjects:
- kind: ServiceAccount
  name: {{ template "tsuru.fullname" . }}-kubernetes-router
  namespace: default
{{- end -}}
